# Generated by Django 2.0.3 on 2018-03-21 22:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pelicula', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('codigo', models.IntegerField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=150)),
            ],
        ),
        migrations.AddField(
            model_name='pelicula',
            name='genero',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='pelicula.Genero'),
        ),
    ]
