# Generated by Django 2.0.3 on 2018-04-11 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pelicula', '0003_auto_20180407_1930'),
    ]

    operations = [
        migrations.AddField(
            model_name='prestamo',
            name='codigoprest',
            field=models.IntegerField(null=True),
        ),
    ]
