# Generated by Django 2.0.3 on 2018-04-14 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pelicula', '0004_prestamo_codigoprest'),
    ]

    operations = [
        migrations.AddField(
            model_name='pelicula',
            name='alquilada',
            field=models.BooleanField(default=False),
        ),
    ]
