# Generated by Django 2.0.3 on 2018-04-14 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pelicula', '0006_auto_20180414_2207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pelicula',
            name='estreno',
            field=models.DateField(help_text='Ej: Mes/Dia/Año', null=True),
        ),
        migrations.AlterField(
            model_name='pelicula',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
